#!/bin/bash
SCRIPT=${0##*/}
SCRIPT_VERSION="1.0"

DIRS=`cat << EOF
/tmp/P2-RPi-ioT-gateway
/var/P2-RPi-ioT-gateway
/var/P2-RPi-ioT-gateway/control
/var/P2-RPi-ioT-gateway/status
/var/log/P2-RPi-ioT-gateway
/var/P2-RPi-ioT-gateway/mail
/var/P2-RPi-ioT-gateway/proc
EOF
`

for DIR in $DIRS; do
    echo "* ${DIR}:"
    ls -lF ${DIR}
    echo ""
done
